#ifndef __XACT_PROJECT_CROWD__
#define __XACT_PROJECT_CROWD__

typedef enum
{
    XACT_WAVEBANK_CROWD_BAD_LOUSY = 0,
    XACT_WAVEBANK_CROWD_BAD_OK = 1,
    XACT_WAVEBANK_CROWD_CLAP1 = 2,
    XACT_WAVEBANK_CROWD_CLAP2 = 3,
    XACT_WAVEBANK_CROWD_CLAP3 = 4,
    XACT_WAVEBANK_CROWD_CLAP4 = 5,
    XACT_WAVEBANK_CROWD_GOOD_GREAT = 6,
    XACT_WAVEBANK_CROWD_GOOD_OK = 7,
    XACT_WAVEBANK_CROWD_GREAT_GOOD = 8,
    XACT_WAVEBANK_CROWD_LOUSY_BAD = 9,
    XACT_WAVEBANK_CROWD_NEG_1 = 10,
    XACT_WAVEBANK_CROWD_NEG_2 = 11,
    XACT_WAVEBANK_CROWD_NEG_3 = 12,
    XACT_WAVEBANK_CROWD_NEG_4 = 13,
    XACT_WAVEBANK_CROWD_NEG_5 = 14,
    XACT_WAVEBANK_CROWD_NEG_6 = 15,
    XACT_WAVEBANK_CROWD_NEG_7 = 16,
    XACT_WAVEBANK_CROWD_NEG_8 = 17,
    XACT_WAVEBANK_CROWD_NEG_9 = 18,
    XACT_WAVEBANK_CROWD_NEG_10 = 19,
    XACT_WAVEBANK_CROWD_OK_BAD = 20,
    XACT_WAVEBANK_CROWD_OK_GOOD = 21,
    XACT_WAVEBANK_CROWD_POS_1 = 22,
    XACT_WAVEBANK_CROWD_POS_2 = 23,
    XACT_WAVEBANK_CROWD_POS_3 = 24,
    XACT_WAVEBANK_CROWD_POS_4 = 25,
    XACT_WAVEBANK_CROWD_POS_5 = 26,
    XACT_WAVEBANK_CROWD_POS_6 = 27,
    XACT_WAVEBANK_CROWD_POS_7 = 28,
    XACT_WAVEBANK_CROWD_POS_8 = 29,
    XACT_WAVEBANK_CROWD_POS_9 = 30,
    XACT_WAVEBANK_CROWD_POS_10 = 31,
    XACT_WAVEBANK_CROWD_GREAT_LOOP = 32,
    XACT_WAVEBANK_CROWD_GOOD_LOOP = 33,
} XACT_WAVEBANK_CROWD;

#define XACT_WAVEBANK_CROWD_ENTRY_COUNT 34

typedef enum
{
    XACT_SOUNDBANK_CROWD_BAD_LOUSY = 0,
    XACT_SOUNDBANK_CROWD_BAD_OK = 1,
    XACT_SOUNDBANK_CROWD_CLAP1 = 2,
    XACT_SOUNDBANK_CROWD_CLAP2 = 3,
    XACT_SOUNDBANK_CROWD_CLAP3 = 4,
    XACT_SOUNDBANK_CROWD_CLAP4 = 5,
    XACT_SOUNDBANK_CROWD_GOOD_GREAT = 6,
    XACT_SOUNDBANK_CROWD_GOOD_OK = 7,
    XACT_SOUNDBANK_CROWD_GREAT_GOOD = 8,
    XACT_SOUNDBANK_CROWD_LOUSY_BAD = 9,
    XACT_SOUNDBANK_CROWD_NEG_1 = 10,
    XACT_SOUNDBANK_CROWD_NEG_2 = 11,
    XACT_SOUNDBANK_CROWD_NEG_3 = 12,
    XACT_SOUNDBANK_CROWD_NEG_4 = 13,
    XACT_SOUNDBANK_CROWD_NEG_5 = 14,
    XACT_SOUNDBANK_CROWD_NEG_6 = 15,
    XACT_SOUNDBANK_CROWD_NEG_7 = 16,
    XACT_SOUNDBANK_CROWD_NEG_8 = 17,
    XACT_SOUNDBANK_CROWD_NEG_9 = 18,
    XACT_SOUNDBANK_CROWD_NEG_10 = 19,
    XACT_SOUNDBANK_CROWD_OK_BAD = 20,
    XACT_SOUNDBANK_CROWD_OK_GOOD = 21,
    XACT_SOUNDBANK_CROWD_POS_1 = 22,
    XACT_SOUNDBANK_CROWD_POS_2 = 23,
    XACT_SOUNDBANK_CROWD_POS_3 = 24,
    XACT_SOUNDBANK_CROWD_POS_4 = 25,
    XACT_SOUNDBANK_CROWD_POS_5 = 26,
    XACT_SOUNDBANK_CROWD_POS_6 = 27,
    XACT_SOUNDBANK_CROWD_POS_7 = 28,
    XACT_SOUNDBANK_CROWD_POS_8 = 29,
    XACT_SOUNDBANK_CROWD_POS_9 = 30,
    XACT_SOUNDBANK_CROWD_POS_10 = 31,
    XACT_SOUNDBANK_CROWD_GOOD_LOOP = 32,
    XACT_SOUNDBANK_CROWD_GREAT_LOOP = 33,
} XACT_SOUNDBANK_CROWD;

#define XACT_SOUNDBANK_CROWD_CUE_COUNT 34

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_BAD_LOUSY_SOUND_BAD_LOUSY = 0,
} XACT_SOUNDBANK_CROWD_CUE_BAD_LOUSY_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_BAD_LOUSY_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_BAD_OK_SOUND_BAD_OK = 0,
} XACT_SOUNDBANK_CROWD_CUE_BAD_OK_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_BAD_OK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_CLAP1_SOUND_CLAP1 = 0,
} XACT_SOUNDBANK_CROWD_CUE_CLAP1_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_CLAP1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_CLAP2_SOUND_CLAP2 = 0,
} XACT_SOUNDBANK_CROWD_CUE_CLAP2_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_CLAP2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_CLAP3_SOUND_CLAP3 = 0,
} XACT_SOUNDBANK_CROWD_CUE_CLAP3_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_CLAP3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_CLAP4_SOUND_CLAP4 = 0,
} XACT_SOUNDBANK_CROWD_CUE_CLAP4_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_CLAP4_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_GOOD_GREAT_SOUND_GOOD_GREAT = 0,
} XACT_SOUNDBANK_CROWD_CUE_GOOD_GREAT_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_GOOD_GREAT_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_GOOD_OK_SOUND_GOOD_OK = 0,
} XACT_SOUNDBANK_CROWD_CUE_GOOD_OK_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_GOOD_OK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_GREAT_GOOD_SOUND_GREAT_GOOD = 0,
} XACT_SOUNDBANK_CROWD_CUE_GREAT_GOOD_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_GREAT_GOOD_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_LOUSY_BAD_SOUND_LOUSY_BAD = 0,
} XACT_SOUNDBANK_CROWD_CUE_LOUSY_BAD_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_LOUSY_BAD_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_1_SOUND_NEG_1 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_1_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_2_SOUND_NEG_2 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_2_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_3_SOUND_NEG_3 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_3_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_4_SOUND_NEG_4 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_4_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_4_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_5_SOUND_NEG_5 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_5_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_5_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_6_SOUND_NEG_6 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_6_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_6_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_7_SOUND_NEG_7 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_7_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_7_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_8_SOUND_NEG_8 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_8_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_8_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_9_SOUND_NEG_9 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_9_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_9_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_NEG_10_SOUND_NEG_10 = 0,
} XACT_SOUNDBANK_CROWD_CUE_NEG_10_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_NEG_10_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_OK_BAD_SOUND_OK_BAD = 0,
} XACT_SOUNDBANK_CROWD_CUE_OK_BAD_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_OK_BAD_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_OK_GOOD_SOUND_OK_GOOD = 0,
} XACT_SOUNDBANK_CROWD_CUE_OK_GOOD_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_OK_GOOD_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_1_SOUND_POS_1 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_1_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_2_SOUND_POS_2 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_2_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_3_SOUND_POS_3 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_3_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_4_SOUND_POS_4 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_4_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_4_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_5_SOUND_POS_5 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_5_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_5_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_6_SOUND_POS_6 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_6_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_6_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_7_SOUND_POS_7 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_7_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_7_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_8_SOUND_POS_8 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_8_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_8_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_9_SOUND_POS_9 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_9_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_9_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_POS_10_SOUND_POS_10 = 0,
} XACT_SOUNDBANK_CROWD_CUE_POS_10_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_POS_10_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_GOOD_LOOP_SOUND_GOOD_LOOP = 0,
} XACT_SOUNDBANK_CROWD_CUE_GOOD_LOOP_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_GOOD_LOOP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_CUE_GREAT_LOOP_SOUND_GREAT_LOOP = 0,
} XACT_SOUNDBANK_CROWD_CUE_GREAT_LOOP_SOUND;

#define XACT_SOUNDBANK_CROWD_CUE_GREAT_LOOP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_BAD_LOUSY_TRACK_0_WAVE_BAD_LOUSY = 0,
} XACT_SOUNDBANK_CROWD_SOUND_BAD_LOUSY_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_BAD_LOUSY_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_BAD_OK_TRACK_0_WAVE_BAD_OK = 0,
} XACT_SOUNDBANK_CROWD_SOUND_BAD_OK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_BAD_OK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_CLAP1_TRACK_0_WAVE_CLAP1 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_CLAP1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_CLAP1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_CLAP2_TRACK_0_WAVE_CLAP2 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_CLAP2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_CLAP2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_CLAP3_TRACK_0_WAVE_CLAP3 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_CLAP3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_CLAP3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_CLAP4_TRACK_0_WAVE_CLAP4 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_CLAP4_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_CLAP4_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_GOOD_GREAT_TRACK_0_WAVE_GOOD_GREAT = 0,
} XACT_SOUNDBANK_CROWD_SOUND_GOOD_GREAT_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_GOOD_GREAT_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_GOOD_OK_TRACK_0_WAVE_GOOD_OK = 0,
} XACT_SOUNDBANK_CROWD_SOUND_GOOD_OK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_GOOD_OK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_GREAT_GOOD_TRACK_0_WAVE_GREAT_GOOD = 0,
} XACT_SOUNDBANK_CROWD_SOUND_GREAT_GOOD_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_GREAT_GOOD_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_LOUSY_BAD_TRACK_0_WAVE_LOUSY_BAD = 0,
} XACT_SOUNDBANK_CROWD_SOUND_LOUSY_BAD_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_LOUSY_BAD_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_1_TRACK_0_WAVE_NEG_1 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_2_TRACK_0_WAVE_NEG_2 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_3_TRACK_0_WAVE_NEG_3 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_4_TRACK_0_WAVE_NEG_4 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_4_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_4_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_5_TRACK_0_WAVE_NEG_5 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_5_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_5_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_6_TRACK_0_WAVE_NEG_6 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_6_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_6_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_7_TRACK_0_WAVE_NEG_7 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_7_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_7_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_8_TRACK_0_WAVE_NEG_8 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_8_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_8_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_9_TRACK_0_WAVE_NEG_9 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_9_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_9_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_NEG_10_TRACK_0_WAVE_NEG_10 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_NEG_10_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_NEG_10_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_OK_BAD_TRACK_0_WAVE_OK_BAD = 0,
} XACT_SOUNDBANK_CROWD_SOUND_OK_BAD_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_OK_BAD_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_OK_GOOD_TRACK_0_WAVE_OK_GOOD = 0,
} XACT_SOUNDBANK_CROWD_SOUND_OK_GOOD_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_OK_GOOD_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_1_TRACK_0_WAVE_POS_1 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_2_TRACK_0_WAVE_POS_2 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_3_TRACK_0_WAVE_POS_3 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_4_TRACK_0_WAVE_POS_4 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_4_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_4_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_5_TRACK_0_WAVE_POS_5 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_5_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_5_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_6_TRACK_0_WAVE_POS_6 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_6_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_6_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_7_TRACK_0_WAVE_POS_7 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_7_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_7_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_8_TRACK_0_WAVE_POS_8 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_8_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_8_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_9_TRACK_0_WAVE_POS_9 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_9_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_9_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_POS_10_TRACK_0_WAVE_POS_10 = 0,
} XACT_SOUNDBANK_CROWD_SOUND_POS_10_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_POS_10_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_GOOD_LOOP_TRACK_0_WAVE_GOOD_LOOP = 0,
} XACT_SOUNDBANK_CROWD_SOUND_GOOD_LOOP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_GOOD_LOOP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_CROWD_SOUND_GREAT_LOOP_TRACK_0_WAVE_GREAT_LOOP = 0,
} XACT_SOUNDBANK_CROWD_SOUND_GREAT_LOOP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_CROWD_SOUND_GREAT_LOOP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_CATEGORY_CLAP1 = 0,
    XACT_CATEGORY_CLAP2 = 1,
    XACT_CATEGORY_CLAP3 = 2,
    XACT_CATEGORY_CLAP4 = 3,
    XACT_CATEGORY_GOOD_LOOP = 4,
    XACT_CATEGORY_GREAT_LOOP = 5,
    XACT_CATEGORY_VENUE_LOOP = 6,
} XACT_CATEGORY;

#define XACT_CATEGORY_COUNT 7

#endif // __XACT_PROJECT_CROWD__
